### ISSUE TITLE
Paste must be extended to any contenteditable element? 

### ISSUE THREAD

**Issue by hemanth** [agektmr/MarkdownPastr#2]
Say for example if one is pasting data to content of  https://gist.github.com/ 

[#L23](https://github.com/agektmr/MarkdownPastr/blob/master/src/js/content_script.js#L23) must be changed?

**Comment by agektmr** [comment]
I haven't looked into the source code deeply, but this doesn't seem like using contenteditable.
This kind of implementation (gist) seems like catching paste event just like this extension do and insert the clipboard content into div content as DOM node.
If my assumption is correct, it is not easy to do what you would expect to happen on textarea.

One work around is to create sandbox where you can paste original rich text onto textarea, then copy & paste that markdown as is.

**Comment by hemanth** [comment]
Yes did notice that github is using a div. Was also trying to figure out a workaround. It's pretty tough here.

**Comment by agektmr** [comment]
If I could modify clipboard content, it's much easier, but not possible. Use description part of gist.github.com as temporary convert sandbox.

**Comment by hemanth** [comment]
:+1:
