### ISSUE TITLE
StartFragmet...EndFragment

### ISSUE THREAD

**Issue by hemanth** [agektmr/MarkdownPastr#3]
StartFragment**Gist** is a simple way to **share snippets and pastes** with others. All gists are git repositories, so they are automatically **versioned**, **forkable** and usable as a **git repository**
.EndFragment

Just tired copy pasting some sample text in gist description, getting the converted text between StartFrgment and EndFragment, is it a feature?

**Comment by agektmr** [comment]
Yes. This extension converts any pasted clipboard content (text/html) into markdown whenever the target is <textarea>.

**Comment by hemanth** [comment]
True, but I noticed those placeholders StartFragmet...EndFragment after pasting the content to a textarea, as in the copied content did not have them, but after pasting they popped in.

**Comment by agektmr** [comment]
I'm confused. I'm not sure what are those "StartFragment" and "EndFragment" thingies are. It is not intended.

**Comment by hemanth** [comment]
When I had copy pasted the content to gist description <textarea> I was getting those text also! Now not able to repro, as it was from another machine will check from there later and re-confirm.

**Comment by hemanth** [comment]
1.0.0 on `Version 25.0.1363.0 canary` i'm noticing this issue.

**Comment by agektmr** [comment]
Unfortunately, I'm already on `Version 25.0.1364.1 canary` and can't reproduce it on Mac. Which platform are you on?

**Comment by hemanth** [comment]
GNU/Linux, I think it's interference of another plugin. Will close the issue as of now. :+1:
