### ISSUE TITLE
Context menu needed? 

### ISSUE THREAD

**Issue by hemanth** [agektmr/MarkdownPastr#5]
Sometimes pasting in certain textareas must be plain text, but with this plugin enabled it's not easy to toggle b/w plain and md...so if there is a context menu like paste-md or something similar, will it be useful?

**Comment by agektmr** [comment]
@hemanth Agreed. How about shift-pasting to unable Markdown-ize as an option?

**Comment by hemanth** [comment]
@agektmr Shift-pasting is also a good move, but the user needs to get used to it. Context-menu will be more dominating if one is doing a right click paste, if not shift+ctrl+v would be Markdown-ized?

**Comment by agektmr** [comment]
On Chrome,
- Shift+V = Paste
- Shift+Command+V = Paste and Match Style

thus,
- Shift+V = Paste Markdown-ized text
- Shift+Command+V = Paste plain text

seems like the most intuitive approach for me.
Plus context menu would be helpful. WDYT?

**Comment by hemanth** [comment]
:+1:

**Comment by agektmr** [comment]
Sorry for belated update but this issue has been resolved as 687c6c7e148d349cb39679d45f94584b15f40a83 is implemented.
